language: python
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: false
# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest test/test_*.py
