services:
    cat-server-runner:
        image: tycho-cat-server
        container_name: tycho-cat-server
        command: server
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
               srcpath: tychoCatServer        
        ports:
        - 9000:9000
        volumes:
            - tycho-cat-server-data:/app/var
            - ./config:/app/config

volumes:
        tycho-cat-server-data: {}

