version: '3'
services:
    tycho-cat-server-runner:
        image: docker_tycho-cat-server
        container_name: tycho-cat-server
        ports:
        - 9000:9000
        volumes:
            - tycho-cat-server-data:/app/var
        links:
            - tycho-cat-server

    tycho-cat-server:
        container_name: tycho-downloader
        build:
            context: ../
        command: downloader.py
        volumes:
            - tycho-cat-server-data:/app/var

volumes:
        tycho-cat-server-data: {}

