version: '3'
services:
    tycho-cat-server-runner:
        image: docker_tycho-cat-server
        container_name: tycho-cat-server
        ports:
        - 9000:9000
        volumes:
            - tycho-cat-server-data:/app/var
            - ../config:/app/config
        links:
            - tycho-cat-server

    tycho-cat-server:
        container_name: tycho-downloader
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
               srcpath: code
        command: python3 code/downloader.py
        volumes:
            - tycho-cat-server-data:/app/var
            - ../config:/app/config

    tycho-cat-server-updater:
        image: docker_tycho-cat-server
        container_name: tycho-updater
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
               srcpath: code
        command: python3 code/updater.py
        volumes:
            - tycho-cat-server-data:/app/var
            - ../config:/app/config
        links:
            - tycho-cat-server

volumes:
        tycho-cat-server-data: {}

