services:
    tycho-cat-server-runner:
        image: docker-tycho-cat-server
        container_name: tycho-cat-server
        command: python3 code/tychoCatServer.py
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
               srcpath: code        
        ports:
        - 9000:9000
        volumes:
            - tycho-cat-server-data:/app/var
            - ../config:/app/config
        profiles:
            - default


    tycho-cat-server:
        image: docker-tycho-cat-server
        container_name: tycho-downloader
        command: python3 code/downloader.py
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
               srcpath: code         
        volumes:
            - tycho-cat-server-data:/app/var
            - ../config:/app/config
        profiles: [init]

    tycho-cat-server-updater:
        image: docker-tycho-cat-server
        container_name: tycho-updater
        command: python3 code/updater.py
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
               srcpath: code         
        volumes:
            - tycho-cat-server-data:/app/var
            - ../config:/app/config
        profiles: [updater]

volumes:
        tycho-cat-server-data: {}

